### ISSUE TITLE
Links on twitter truncated

### ISSUE THREAD

**Issue by iriscal** [retrospring/bugs#89] opened 2015-03-11 13:48 UTC
Links on twitter get truncated when the Post To Twitter option is enabled. I recently posted an answer with a link that was too long, and clicking the tweet on twitter links to the wrong webpage. Can you make it so that links posted in answers get put through a URL shortener, and if there's not enough room for the link before truncation, just hide the entire link on tweeted answers?

**Comment by pixeldesu** [comment] 2015-03-11 13:50
Duplicate of #46

**Closed by pixeldesu** 2015-03-11 13:50 UTC
Labels: duplicate
