### ISSUE TITLE
Search functionality

### ISSUE THREAD

**Issue by Syncro9** [Retrospring/bugs#79] opened 2015-06-10 01:20 UTC
Retrospring needs a search box, manually going through your questions/answers page takes too long.

It would also be nice if you could search for users as well.

**Comment by yukimono** [comment] 2015-06-10 02:52
Last time I checked we were planning to do something with [ElasticSearch](https://github.com/elastic/elasticsearch), i'll check if that's still the case, if not i'll try to convince everyone to use [sphinx search](http://sphinxsearch.com)

ElasticSearch requires java ;-;

**Comment by yukimono** [comment] 2015-06-10 03:02
paging @pixeldesu

**Comment by yukimono** [comment] 2015-06-10 03:05
Also, for search queries i recommend we try to implement something like

(at an extreme case)

`text !"not this string" ~fuzzy ^"or this" asker:name user:name smiles:>5 answers:>5 age:">2 weeks"`

**Comment by yukimono** [comment] 2015-06-10 03:47
`search_query_lexer.rb`

```ruby
def search_query_lexer(query)
  n = 0
  result = {
    query: [],
    commands: []
  }
          #not  , fuzzy, or
  flags = [false, false, false]
  chars = []
  while n < query.length
    char = query[n]
    case char.downcase
    when '!'
      flags[0] = !flags[0]
    when '~'
      flags[1] = !flags[1]
    when '^'
      flags[2] = !flags[2]
    when '"' || "'"
      index = query.index char, n + 1
      index = query.length if index.nil?

      chars.push query[n + 1..index - 1].split ''

      n = index
    when /\s/
      if chars.length > 0
        if not result[:query].last.nil? and result[:query].last[:flags].join('') == flags.join('')
          result[:query].last[:chars] += " #{chars.flatten.join ''}"
        else
          result[:query].push({flags: flags, chars: chars.flatten.join('')})
        end

        flags = [false, false, false]
        chars = []
      end
    else
      space_index = query.index /\s/, n + 1
      column_index = query.index ':', n + 1
      if not column_index.nil? and (space_index.nil? or space_index > column_index)
        column = query[n..column_index-1]
        end_of_command = space_index
        if query[column_index + 1] == '"' or query[column_index + 1] == "'"
          column_index += 1
          end_of_command = query.index query[column_index], column_index + 1
        end
        end_of_command = query.length if end_of_command.nil?
        command = query[column_index + 1..end_of_command-1]
        m = 0
        command_param = ''
        while m < command.length
          case command[m]
          when '>'
            command_param += 'gt'
          when '<'
            command_param += 'lt'
          when '='
            command_param += 'e'
          else
            result[:commands].push({op: command_param, command: column, param: command[m..command.length]})
            m = command.length
          end
          m += 1
        end
        n = end_of_command
      else
        chars.push char
      end
    end
    n += 1
  end
  if chars.length > 0
    if not result[:query].last.nil? and result[:query].last[:flags].join('') == flags.join('')
      result[:query].last[:chars] += " #{chars.flatten.join ''}"
    else
      result[:query].push({flags: flags, chars: chars.flatten.join('')})
    end
  end
  result
end

puts search_query_lexer 'a test string with:>=command !"nested command:yes" ~^fuzzy ~^or'
```

in yaml it looks like
```yaml
---
:query:
- :flags:
  - false
  - false
  - false
  :chars: a test string
- :flags:
  - true
  - false
  - false
  :chars: nested command:yes
- :flags:
  - false
  - true
  - true
  :chars: fuzzy or
:commands:
- :op: gte
  :command: with
  :param: command
```

**Comment by nilsding** [comment] 2015-06-10 11:50
On Tuesday 09 Jun 2015 19:52:42 Yuki wrote:
> ElasticSearch requires java ;-;

And ElasticSearch is already installed on the server Retrospring runs on.

**Comment by TheCoward** [comment] 2015-06-25 00:43
beep boop dupe of #20

i'm a visionary though

**Comment by yukimono** [comment] 2015-06-25 03:41
duplicate of #20

**Closed by yukimono** 2015-06-25 03:41 UTC
Labels: backend, discussion, feature request, help wanted, user experience
