### ISSUE TITLE
Streamline notifications

### ISSUE THREAD

**Issue by Filippus** [Retrospring/bugs#38] opened 2015-04-26 15:59 UTC
Basically, a system similar to Twitter's notifications. For example, if multiple people answer to the same question, it merges them into a single notification ("person x and y other people answered to...) instead of having a lot of clutter notifications. Clicking the notification leads to the question page with all the answers visible (and the new ones marked with color or something). 

Should also apply to follower/comment/smile notifications.

**Comment by yukimono** [comment] 2015-04-28 04:38
I'd have to figure out how to do proper grouping in rails, but i've been wanting to implement this for a while, along with completely rewriting the notifications dropdown to be more interactive.

**Comment by TheCoward** [comment] 2015-06-08 21:58
Just noticed this, and remember I had mentioned that back in #10. Not relevant, but still funny to point it out :>

**Comment by yukimono** [comment] 2015-06-09 06:14
Duplicate of #10 (derp)

**Closed by yukimono** 2015-06-09 06:14 UTC
Labels: design, enhancement, user experience
