### ISSUE TITLE
real time inbox notification updates

### ISSUE THREAD

**Issue by squezey** [retrospring/bugs#38] opened 2015-01-02 17:54 UTC
I noticed there's no real time notifications that appear in your inbox and the page needs to be refreshed to get any updates to it. If there's a way to I think it should be done in real time, it would be more helpful to people that leave the site open in another tab/window that wouldn't know that got anything until they decided to refresh the page and feel much more fluid overall to the experience.

**Comment by nilsding** [comment] 2015-01-02 19:01
pretty much a dupe of #32.  it's a thing that's being worked on.

**Closed by nilsding** 2015-01-02 19:01 UTC
Labels: duplicate
